# Generated by Django 6.0.6 on 2026-06-17 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFFResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('response_time', models.FloatField()),
                ('is_correct', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbc.player')),
            ],
        ),
    ]
